[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[target.aarch64-apple-darwin]
rustflags = ["--cfg", "erase_components"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "erase_components"]
